import { writeFileSync } from 'node:fs';
const string={type:'string'},boolean={type:'boolean'},uuid={type:'string',format:'uuid'},amount={type:'integer',minimum:0,description:'Тыйын: 13000 = 130 сом'},localized={type:'object',required:['ru'],properties:{ru:string,ky:string,en:string},additionalProperties:false};
const object=(properties,required=[])=>({type:'object',properties,...(required.length?{required}:{}),additionalProperties:false});
const schemas={
 OtpRequest:object({phone:{type:'string',pattern:'^\\+996\\d{9}$'},consent:{type:'boolean',enum:[true]}},['phone','consent']),
 OtpVerify:object({phone:string,code:{type:'string',pattern:'^\\d{4}$'}},['phone','code']),
 StaffLogin:object({phone:string,password:{type:'string',format:'password'}},['phone','password']),
 Refresh:object({refreshToken:string},['refreshToken']),
 Profile:object({firstName:string,lastName:string,language:{type:'string',enum:['ru','ky','en']},email:{type:'string',format:'email',nullable:true}}),
 Address:object({label:string,street:string,latitude:{type:'number',minimum:-90,maximum:90},longitude:{type:'number',minimum:-180,maximum:180},entrance:string,intercom:string,floor:string,apartment:string,comment:string},['street','latitude','longitude']),
 CartItem:object({storeId:uuid,quantity:{type:'integer',minimum:1,maximum:100}},['storeId','quantity']),
 Checkout:object({addressId:uuid,paymentMethod:{type:'string',enum:['CASH','QR']},email:{type:'string',format:'email'},courierComment:string,cashChangeFrom:amount,promoCode:string,ageConfirmed:boolean},['addressId','paymentMethod']),
 Rating:object({score:{type:'integer',minimum:1,maximum:5},comment:string},['score']),
 PickItem:{oneOf:[object({action:{type:'string',enum:['PICK']}},['action']),object({action:{type:'string',enum:['EXCLUDE']}},['action']),object({action:{type:'string',enum:['PROPOSE_REPLACEMENT']},productId:uuid},['action','productId'])]},
 Replacement:object({accept:boolean},['accept']),
 PaymentEvent:object({eventId:string,paymentId:uuid,status:{type:'string',enum:['PAID','FAILED']},amount},['eventId','paymentId','status','amount']),
 MockPayment:object({status:{type:'string',enum:['PAID','FAILED'],default:'PAID'}}),
 Thread:object({orderId:uuid,message:string},['message']),Message:object({message:string},['message']),ThreadStatus:object({status:{type:'string',enum:['OPEN','CLOSED']}},['status']),
 Category:object({name:localized,sort:{type:'integer',minimum:0}},['name']),
 Product:object({categoryId:uuid,name:localized,description:{type:'object',properties:{ru:string,ky:string,en:string}},composition:{type:'object',properties:{ru:string,ky:string,en:string}},nutrition:object({calories:{type:'number',minimum:0},protein:{type:'number',minimum:0},fat:{type:'number',minimum:0},carbohydrates:{type:'number',minimum:0}}),unit:string,imageUrl:{type:'string',format:'uri',nullable:true},isNew:boolean,ageRestricted:boolean,active:boolean},['categoryId','name','unit']),
 Inventory:object({storeId:uuid,productId:uuid,price:amount,stock:{type:'integer',minimum:0}},['storeId','productId','price','stock']),
 Store:object({name:string,address:string,latitude:{type:'number'},longitude:{type:'number'},radiusKm:{type:'number',minimum:0,exclusiveMinimum:true},deliveryFee:amount,minimumOrder:amount,opensAt:{type:'string',example:'09:00'},closesAt:{type:'string',example:'01:00'},active:boolean},['name','address','latitude','longitude','radiusKm','deliveryFee','opensAt','closesAt']),
 Staff:object({phone:string,password:{type:'string',minLength:12,maxLength:128,format:'password'},role:{type:'string',enum:['PICKER','COURIER','ADMIN']},firstName:string,lastName:string,storeIds:{type:'array',items:uuid,minItems:1}},['phone','password','role','firstName','storeIds']),
 StaffUpdate:object({active:boolean,password:{type:'string',minLength:12,maxLength:128,format:'password'},storeIds:{type:'array',items:uuid,minItems:1}}),
 Promotion:object({code:string,kind:{type:'string',enum:['PERCENT','FIXED','FREE_DELIVERY','GIFT']},value:{type:'integer',minimum:0,description:'Для PERCENT: 0–100. Для FIXED: тыйын.'},minimumOrder:amount,startsAt:{type:'string',format:'date-time'},endsAt:{type:'string',format:'date-time'},usageLimit:{type:'integer',minimum:1},giftProductId:uuid,triggerProductIds:{type:'array',items:uuid}},['code','kind','startsAt','endsAt','usageLimit']),
 PromotionToggle:object({active:boolean},['active']),
 Content:object({kind:{type:'string',enum:['BANNER','STORY','NOTICE','DOCUMENT','COLLECTION']},title:localized,body:{type:'object',properties:{ru:string,ky:string,en:string}},imageUrl:{type:'string',format:'uri',nullable:true},productIds:{type:'array',items:uuid},active:boolean,sort:{type:'integer',minimum:0}},['kind','title']),
 Error:{type:'object',properties:{error:{type:'object',properties:{code:string,message:string,details:{},requestId:string}}}},
 Response:{type:'object',properties:{data:{description:'Результат операции; идентификаторы — UUID, денежные поля — целые значения в тыйынах.'}}}
};
schemas.CreateOrder=object({...schemas.Checkout.properties,expectedTotal:amount},[...schemas.Checkout.required,'expectedTotal']);
const spec={openapi:'3.0.3',info:{title:'Бекбекей · API доставки продуктов',version:'0.1.0',description:'Рабочий MVP по PDF-макету. SMS выводятся только в серверный лог. QR-платежи и возвраты — тестовая имитация. Цены передаются в тыйынах (KGS × 100). Вход: opaque Bearer access token на 15 минут, refresh token на 30 дней. Поля запросов — camelCase; SQL-ответы — snake_case. Списки: limit/offset. Перед оформлением запросите checkout/quote.'},servers:[{url:'http://localhost:3000'}],tags:['Auth','Catalog','Customer','Orders','Payments','Picking','Delivery','Courier','Support','Admin','Events','System'].map(name=>({name})),components:{securitySchemes:{bearerAuth:{type:'http',scheme:'bearer',description:'accessToken из ответа авторизации'}},schemas},paths:{}};
const ref=name=>({$ref:`#/components/schemas/${name}`});
function route(method,path,tag,summary,{body,role='PUBLIC',status=200,query=[],key=false,description='',raw=false}={}){
 const parameters=[];
 for(const m of path.matchAll(/\{([^}]+)\}/g))parameters.push({in:'path',name:m[1],required:true,schema:m[1]==='code'?string:uuid});
 for(const [name,schema,required=false] of query)parameters.push({in:'query',name,required,schema});
 if(key)parameters.push({in:'header',name:'Idempotency-Key',required:true,schema:{type:'string',minLength:8,maxLength:128},description:'Уникальный ключ логической операции. При повторе используйте тот же ключ.'});
 if(raw)parameters.push({in:'header',name:'X-Payment-Signature',required:true,schema:string,description:'Hex HMAC-SHA256 от точных байтов JSON, секрет PAYMENT_WEBHOOK_SECRET'});
 const responses={[status]:{description:status===204?'Операция выполнена':'Успешный ответ',...(status!==204?{content:{'application/json':{schema:ref('Response')}}}:{})}};
 for(const code of [400,401,403,404,409,422,429,500,503])responses[code]={description:({400:'Неверный код или JSON',401:'Требуется вход',403:'Недостаточно прав',404:'Запись не найдена',409:'Конфликт состояния, цены или остатков',422:'Ошибка проверки данных',429:'Ограничение частоты',500:'Ошибка сервера',503:'Интеграция отключена'})[code],content:{'application/json':{schema:ref('Error')}}};
 const op={tags:[tag],summary,description:`Роль: ${role}. ${description}`,operationId:`${method}_${path.replace(/[^a-zA-Z0-9]/g,'_')}`,security:role==='PUBLIC'?[]:[{bearerAuth:[]}],parameters,responses};
 if(body)op.requestBody={required:true,content:{'application/json':{schema:ref(body)}}};
 (spec.paths[path]??={})[method]=op;
}
const pag=[['limit',{type:'integer',minimum:1,maximum:100,default:30}],['offset',{type:'integer',minimum:0,default:0}]];
const store=[['storeId',uuid,true]],products=[...store,['categoryId',uuid],['search',string],['language',{type:'string',enum:['ru','ky','en']}],['filter',{type:'string',enum:['all','new']}],...pag];
const base='/api/v1';
const add=(method,path,tag,title,options)=>route(method,base+path,tag,title,options);
route('get','/health','System','Жив ли процесс');route('get','/ready','System','Доступна ли база данных');
add('post','/auth/otp/request','Auth','Запросить SMS-код',{body:'OtpRequest',status:202,description:'Код не возвращается в API. В режиме разработки смотрите серверный лог. Повтор через 60 секунд, TTL 5 минут.'});
add('post','/auth/otp/verify','Auth','Проверить код и войти',{body:'OtpVerify',description:'Не более 5 попыток. Возвращает accessToken, refreshToken, expiresIn и user.'});
add('post','/auth/staff/login','Auth','Вход сотрудника',{body:'StaffLogin'});add('post','/auth/refresh','Auth','Обновить и ротировать сеанс',{body:'Refresh'});add('post','/auth/logout','Auth','Отозвать сеанс',{role:'ANY',status:204});
add('get','/stores','Catalog','Открытые для обслуживания магазины');add('get','/delivery/availability','Catalog','Проверить зону доставки',{query:[['latitude',{type:'number'},true],['longitude',{type:'number'},true]]});
add('get','/categories','Catalog','Категории');add('get','/products','Catalog','Каталог и поиск',{query:products});add('get','/products/{id}','Catalog','Карточка товара и рекомендации',{query:store});add('get','/home','Catalog','Главная страница',{query:[...store,['language',string]]});add('get','/content','Catalog','Баннеры, истории и документы',{query:[['kind',{type:'string',enum:['BANNER','STORY','NOTICE','DOCUMENT','COLLECTION']}]]});
add('get','/me','Customer','Мой профиль',{role:'ANY'});add('patch','/me','Customer','Изменить профиль',{role:'ANY',body:'Profile'});
add('get','/me/addresses','Customer','Мои адреса',{role:'CUSTOMER'});add('post','/me/addresses','Customer','Сохранить адрес',{role:'CUSTOMER',body:'Address',status:201});add('put','/me/addresses/{id}','Customer','Обновить адрес полностью',{role:'CUSTOMER',body:'Address'});add('delete','/me/addresses/{id}','Customer','Удалить адрес',{role:'CUSTOMER',status:204});
for(const p of ['favorites','purchased'])add('get',`/me/${p}`,'Customer',p==='favorites'?'Избранное':'Ранее купленные товары',{role:'CUSTOMER',query:[...store,...pag]});
add('put','/me/favorites/{id}','Customer','Добавить в избранное',{role:'CUSTOMER',status:204});add('delete','/me/favorites/{id}','Customer','Удалить из избранного',{role:'CUSTOMER',status:204});
add('get','/cart','Orders','Получить корзину',{role:'CUSTOMER'});add('put','/cart/items/{id}','Orders','Установить количество товара',{role:'CUSTOMER',body:'CartItem',status:204});add('delete','/cart/items/{id}','Orders','Удалить позицию',{role:'CUSTOMER',status:204});add('delete','/cart','Orders','Очистить корзину',{role:'CUSTOMER',status:204});
add('post','/checkout/quote','Orders','Рассчитать стоимость заказа',{role:'CUSTOMER',body:'Checkout',description:'Сумма не резервирует товар. Первая активная покупка получает бесплатную доставку.'});
add('post','/orders','Orders','Создать заказ и зарезервировать остатки',{role:'CUSTOMER',body:'CreateOrder',key:true,status:201,description:'expectedTotal берётся из quote. При повторе с тем же ключом возвращается существующий заказ с HTTP 200.'});
add('get','/orders','Orders','История заказов',{role:'CUSTOMER',query:pag});add('get','/orders/{id}','Orders','Заказ, позиции и история статусов',{role:'CUSTOMER'});add('post','/orders/{id}/cancel','Orders','Отменить заказ',{role:'CUSTOMER',description:'Допустимо до READY. Повторная отмена безопасна.'});add('post','/orders/{id}/repeat','Orders','Перенести доступные позиции в пустую корзину',{role:'CUSTOMER',description:'Не создаёт заказ автоматически. Цены проверяются заново.'});add('put','/orders/{id}/rating','Orders','Оценить доставку',{role:'CUSTOMER',body:'Rating',status:204});
add('post','/orders/{id}/items/{itemId}/replacement','Orders','Согласовать или отклонить замену',{role:'CUSTOMER',body:'Replacement'});
add('post','/orders/{id}/payments','Payments','Создать тестовый QR-платёж',{role:'CUSTOMER',key:true,status:201,description:'Тестовый QR payload не является банковским QR. Один незавершённый платёж на заказ.'});add('get','/payments/{id}','Payments','Статус платежа',{role:'Владелец заказа или ADMIN'});add('post','/payments/{id}/mock-confirm','Payments','Подтвердить тестовый платёж',{role:'ADMIN',body:'MockPayment'});add('post','/webhooks/payments/mock','Payments','Подписанное событие тестового платежа',{body:'PaymentEvent',raw:true,description:'Подпись проверяется до чтения JSON. eventId уникален. Повтор с другим содержимым — конфликт.'});
for(const group of ['picking','delivery']){
 const tag=group==='picking'?'Picking':'Delivery',role=group==='picking'?'PICKER':'COURIER';
 add('get',`/${group}/tasks`,tag,'Доступные и назначенные задания',{role,query:pag});add('get',`/${group}/tasks/{id}`,tag,'Моё назначенное задание',{role});add('post',`/${group}/tasks/{id}/claim`,tag,'Атомарно взять задание',{role});
}
add('patch','/picking/tasks/{id}/items/{itemId}','Picking','Собрать, исключить или предложить замену',{role:'PICKER',body:'PickItem',description:'QR-заказ допускает замену только на товар не дороже. Принятая замена считается обработанной позицией.'});add('post','/picking/tasks/{id}/complete','Picking','Завершить сборку',{role:'PICKER'});
for(const [action,summary,status] of [['pickup','Забрать собранный заказ',200],['arrive','Отметить прибытие',204],['confirm-cash','Подтвердить получение наличных',204],['complete','Подтвердить вручение',200],['report-unreachable','Клиент не отвечает: начать ожидание',200],['return','Подтвердить возврат в магазин',200]])add('post',`/delivery/tasks/{id}/${action}`,'Delivery',summary,{role:'COURIER',status});
add('post','/courier/shifts/start','Courier','Начать смену',{role:'COURIER'});add('post','/courier/shifts/end','Courier','Закончить смену',{role:'COURIER',status:204});add('get','/courier/statistics','Courier','Заработок и рейтинг',{role:'COURIER',query:[['period',{type:'string',enum:['today','week','month']}]]});add('get','/courier/history','Courier','История доставки',{role:'COURIER',query:pag});
add('get','/support/threads','Support','Мои обращения, для админа — все',{role:'ANY',query:pag});add('post','/support/threads','Support','Создать обращение',{role:'ANY',body:'Thread',status:201});add('get','/support/threads/{id}/messages','Support','Сообщения обращения',{role:'Владелец или ADMIN',query:pag});add('post','/support/threads/{id}/messages','Support','Написать сообщение',{role:'Владелец или ADMIN',body:'Message',status:201});add('patch','/support/threads/{id}','Support','Закрыть или открыть обращение',{role:'ADMIN',body:'ThreadStatus'});
for(const name of ['summary','orders','stores','categories','products','inventory','staff','promotions','content','refunds','payments','jobs','audit'])add('get',`/admin/${name}`,'Admin',`Управление: ${name}`,{role:'ADMIN',query:['orders','products','inventory','refunds','payments','jobs','audit'].includes(name)?pag:[]});
add('get','/admin/orders/{id}','Admin','Детали любого заказа',{role:'ADMIN'});add('post','/admin/orders/{id}/cancel','Admin','Отменить заказ',{role:'ADMIN'});add('post','/admin/orders/{id}/authorize-return','Admin','Разрешить возврат в магазин',{role:'ADMIN',status:204});
for(const [path,schema] of [['stores','Store'],['categories','Category'],['products','Product'],['content','Content']]){add('post',`/admin/${path}`,'Admin',`Создать: ${path}`,{role:'ADMIN',body:schema,status:201});add('put',`/admin/${path}/{id}`,'Admin',`Обновить полностью: ${path}`,{role:'ADMIN',body:schema});}
add('put','/admin/inventory','Admin','Установить цену и физический остаток',{role:'ADMIN',body:'Inventory',status:204});add('post','/admin/staff','Admin','Создать сотрудника',{role:'ADMIN',body:'Staff',status:201});add('patch','/admin/staff/{id}','Admin','Обновить сотрудника и отозвать его сеансы',{role:'ADMIN',body:'StaffUpdate',status:204});add('post','/admin/promotions','Admin','Создать акцию',{role:'ADMIN',body:'Promotion',status:201});add('patch','/admin/promotions/{code}','Admin','Включить или отключить акцию',{role:'ADMIN',body:'PromotionToggle',status:204});add('post','/admin/jobs/{id}/retry','Admin','Повторить незавершённую задачу',{role:'ADMIN',status:204});
add('get','/events','Events','Поток событий SSE',{role:'ANY',query:[['after',{type:'integer',minimum:0}]],description:'Authorization: Bearer обязателен. Используйте fetch-stream, обычный EventSource не позволяет задать этот заголовок. Переподключение: Last-Event-ID либо after. Поток закрывается при истечении access token.'});
spec.paths['/api/v1/events'].get.responses[200]={description:'SSE: id, event, data',content:{'text/event-stream':{schema:{type:'string'}}}};
spec.paths['/api/v1/orders'].post.responses[200]={description:'Заказ уже создан с этим ключом',content:{'application/json':{schema:ref('Response')}}};
writeFileSync('docs/openapi.json',JSON.stringify(spec,null,2)+'\n');console.log(`${Object.keys(spec.paths).length} путей OpenAPI`);
